### ISSUE TITLE
Check-Ins von Externen erlauben

### ISSUE THREAD

**Issue by jasperroloff** [thomashackl/contact-tracer#10]
Derzeit erfordert das Plugin für den Check-In einen Stud.IP-Account und eine Mitgliedschaft in der Veranstaltung.
Es wäre schön, wenn die QR-Codes auch für Externe, die keinen Stud.IP-Account haben bzw. nicht Mitglied in der Veranstaltung sind, funktionieren würden.

**Comment by thomashackl** [comment]
Da müsste quasi eine Benutzerverwaltung neben Stud.IP aufgezogen werden, damit externe Personen auch über mehrere Präsenztermine hinweg erkannt werden können. Außerdem sind die Termine, zu denen die QR-Codes gehören, an Veranstaltungen gekoppelt, weshalb dort auch nur Mitglieder der Veranstaltung Zugriff auf die Registrierung haben können.
Das lässt sich also nicht wirklich umsetzen.
