### ISSUE TITLE
Plugin erst ab Stud.IP >= 4.5 nutzbar

### ISSUE THREAD

**Issue by pselsa** [thomashackl/contact-tracer#2]
Das Plugin funktioniert erst ab Stud.IP >= 4.5, nicht schon ab 4.2 wie im Manifest angegeben.

Problem ist hier:
`Call to undefined method PageLayout::allowFullscreenMode()`

Diese Funktion wurde erst in 4.5 eingeführt.

**Comment by thomashackl** [comment]
Danke für das Feedback, ist in der aktuellen Version behoben. Jetzt wird überprüft, ob es diese Methode auch wirklich gibt, damit sollte das Plugin in einer 4.2 laufen.

**Comment by pselsa** [comment]
Merci, funktioniert :)
