### ISSUE TITLE
Usability: Menü der Sidebar nach Registrierung

### ISSUE THREAD

**Issue by pselsa** [thomashackl/contact-tracer#6]
Nach der Registrierung baut sich das Menü der Sidebar komisch auf, da dort der Menüpunkt "Registrieren" angewählt ist. Klickt man erneut auf diesen Punkt gibts ne Fehlermeldung. Warum existiert dieser Menüpunkt überhaupt?

Komisch ist das vor allem, wenn man vorher in der Liste der registrierten Personen war, da man danach dort nicht wieder zurück kommt. Man muss dann erst wieder auf QR Code klicken und danach auf die Liste. Das ist von der Usability her unschön, besser wäre hier wenn man wieder direkt in der Liste landet.

**Comment by thomashackl** [comment]
Der Menüpunkt existiert letztlich nur, um zu zeigen, wo man gerade ist. Das mit dem "Rücksprung" ist mir selber noch ein kleiner Dorn im Auge, da wird sich noch was tun.

**Comment by pselsa** [comment]
Könntest du das Registrieren nicht direkt wieder auf den QR Code redirecten und die Meldung dass man sich erfolgreich eingetragen hat einfach dort anzeigen lassen? Dann könnte der ganze Menüpunkt einfach weg und man wüsste ja wegen der Meldung trotzdem was passiert ist.

**Comment by thomashackl** [comment]
Nicht pauschal, man kann sich ja auch für vergangene Termine nachträglich manuell registrieren, und da gibt es dann gar keinen QR-Code.

**Comment by pselsa** [comment]
Ah okay... ich verstehe das Dilemma 🤣  Dann vielleicht generell die Registrierungs-Aktion auf die vorige Seite redirecten? Bei QR Code Scan landet man wieder beim QR Code, beim manuellen Eintragen landet man wieder bei der Terminliste usw.

**Comment by pselsa** [comment]
Sieht gut aus! @thomashackl es gibt aber noch eine Stelle die du vergessen hast: wenn man eine Person aus der Liste wieder austrägt landet man bei Anwesenheit manuell erfassen.
