### ISSUE TITLE
Call to a member function getFullname() on null

### ISSUE THREAD

**Issue by pselsa** [thomashackl/contact-tracer#8]
Klickt man in der Suche auf "Kontakte finden" ohne vorher eine Person eingegeben zu haben, schmeißt das Plugin folgenden Fehler:

![image](https://user-images.githubusercontent.com/53210931/128324241-82f43ce7-fde9-4596-84bf-b329b9fb9dff.png)

Hier sollte eine richtige Fehlermeldung kommen.

**Comment by thomashackl** [comment]
Ist bereits in der aktuellen Pluginversion behoben, diese ist auf dem Pluginmarktplatz verfügbar. Entwicklung findet unter https://gitlab.data-quest.de/studip-plugins-oeffentlich/contact-tracer statt. (ich muss hier mal die Repos aufräumen)

**Comment by pselsa** [comment]
Ah okay, wir nutzten bislang nur diese Repo :D Danke
